# -*- coding: utf-8 -*-
"""Difference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def difference(value_1, value_2):
    result = value_1 - value_2
    return result

value_1 = int(input("Enter the value: "))
value_2 = int(input("Enter the value: "))

print(difference(value_1, value_2))