# -*- coding: utf-8 -*-
"""Modulus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def mod(value_1, value_2):
    result = value_1 % value_2
    return result

print(mod(6543,51))