# -*- coding: utf-8 -*-
"""Product.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def product(value_1, value_2):
    result = value_1 * value_2
    return result

value_1 = int(input("Enter the value: "))
value_2 = int(input("Enter the value: "))

print(product(value_1, value_2))