# -*- coding: utf-8 -*-
"""Sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def perform_sum(value_1, value_2):
    result = value_1 + value_2
    return result

print(perform_sum(5,6))