# -*- coding: utf-8 -*-
"""Sum (user input).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkjbMzRQgziQ_upSKMBK1XzQ0DJkHGai
"""

def perform_sum(value_1, value_2):
    return value_1 + value_2

value_1 = int(input("Enter the value: "))
value_2 = int(input("Enter the value: "))

result = perform_sum(value_1, value_2)
print(result)